### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by HevarKas** [Nelitaa/ToDo-list#2]
# Hi @Nelitaa 

So far, you've done well.

Well, there are some problems you need to fix.

- please add render function to delete function.
- please add cursor: pointer for button.

**Comment by mperezbazan** [comment]
Hi @Nelitaa, your project looks great!
Maybe you can quit the border in the input when is in focus, like the template.

**Comment by lmunozm1702** [comment]
Hi!! great code so far, just a little visual thing, when you click a task to edit them, need to change the background of that item.

**Comment by Nelitaa** [comment]
Done! Thanks
